version: '3'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
